name: Swift Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '6.0'
      continue-on-error: true
    
    - name: Fallback to latest Swift
      if: ${{ failure() }}
      uses: swift-actions/setup-swift@v1
    
    - name: Get Swift version
      id: swift_version
      run: |
        SWIFT_VERSION=$(swift --version | head -n 1 | sed 's/.*Swift version \([0-9.]*\).*/\1/')
        echo "SWIFT_VERSION=$SWIFT_VERSION" >> $GITHUB_ENV
        echo "Swift version: $SWIFT_VERSION"
    
    - name: Update Swift tools version if needed
      run: |
        PACKAGE_SWIFT_VERSION=$(head -n 1 Package.swift | sed 's/\/\/\ swift-tools-version:\([0-9.]*\)/\1/')
        echo "Package Swift version: $PACKAGE_SWIFT_VERSION"
        
        if [ "$PACKAGE_SWIFT_VERSION" != "$SWIFT_VERSION" ]; then
          echo "Updating Swift tools version from $PACKAGE_SWIFT_VERSION to $SWIFT_VERSION"
          sed -i.bak "1s/\/\/\ swift-tools-version:[0-9.]*$/\/\/ swift-tools-version:$SWIFT_VERSION/" Package.swift
          rm Package.swift.bak
        fi
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test 