name: Swift Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
    
    - name: Get Swift version
      id: swift_version
      run: |
        SWIFT_VERSION=$(swift --version | head -n 1 | sed 's/.*Swift version \([0-9.]*\).*/\1/')
        echo "SWIFT_VERSION=$SWIFT_VERSION" >> $GITHUB_ENV
        echo "Swift version: $SWIFT_VERSION"
    
    - name: Update Swift tools version
      run: |
        # Directly update the first line of Package.swift to use the available Swift version
        echo "Updating Swift tools version to $SWIFT_VERSION"
        sed -i.bak "1s|.*|// swift-tools-version:$SWIFT_VERSION|" Package.swift
        cat Package.swift | head -n 5
        rm Package.swift.bak
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test 