name: Swift Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Get Swift version
      run: swift --version
    
    - name: Build
      run: swift build
    
    - name: Run tests
      run: swift test 